---
app_dir: /opt/discord-jobbot
repo_url: https://github.com/Jokr02/job_bot.git

DISCORD_BOT_TOKEN: ""
DISCORD_CHANNEL_ID: ""
SMTP_HOST: ""
SMTP_PORT: "587"
SMTP_USER: ""
SMTP_PASSWORD: ""
SENDER_NAME: "JobBot"
ADZUNA_APP_ID: ""
ADZUNA_APP_KEY: ""
ADZUNA_COUNTRY: "de"
ERROR_WEBHOOK_URL: ""
