---
- name: Deploy Twingate Connector
  ansible.builtin.copy:
    dest: "{{ containers_root }}/twingate/docker-compose.yml"
    mode: "0644"
    content: |
      services:
        twingate:
          image: twingate/connector:latest
          container_name: twingate
          restart: unless-stopped
          environment:
            TWINGATE_NETWORK: "{{ twingate_network }}"
            TWINGATE_ACCESS_TOKEN: "{{ twingate_access_token }}"
            TWINGATE_REFRESH_TOKEN: "{{ twingate_refresh_token }}"
          volumes:
            - ./etc-twingate:/etc/twingate
          network_mode: bridge

- name: Compose up Twingate
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: "{{ containers_root }}/twingate"
