---
- name: Gather system facts
  setup:

# Optional: Check if ZFS exists on system
- name: Check if ZFS is installed
  stat:
    path: /sbin/zfs
  register: zfs_check

# Optional: Create ZFS snapshot only if ZFS exists
- name: Create ZFS snapshot before update
  command: "zfs snapshot rpool/ROOT/pve-1@pre-update-{{ ansible_date_time.iso8601_basic }}"
  when: zfs_check.stat.exists
  ignore_errors: true

# Update package lists
- name: Update APT package index
  apt:
    update_cache: yes

# Perform full system upgrade
- name: Upgrade all packages (dist-upgrade)
  apt:
    upgrade: dist
  register: upgrade_result

# Send Discord Notification
- name: Send Discord notification
  uri:
    url: "{{ discordwebhook }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body: |
      {
        "username": "Proxmox Update",
        "embeds": [
          {
            "title": "✅ Proxmox Host Updated",
            "color": 65280,
            "fields": [
              {"name": "Hostname", "value": "{{ inventory_hostname }}", "inline": true},
              {"name": "Kernel", "value": "{{ ansible_kernel }}", "inline": true},
              {"name": "Changes Applied", "value": "{{ 'Yes' if upgrade_result.changed else 'No' }}", "inline": true}
            ],
            "timestamp": "{{ ansible_date_time.iso8601 }}"
          }
        ]
      }
    body_format: json
    status_code: 204
  delegate_to: localhost
  run_once: true
  ignore_errors: true
  become: false
