---
- name: Ensure required packages
  ansible.builtin.apt:
    name: [ ca-certificates, wget, tar ]
    state: present
    update_cache: yes

- name: Create service user
  ansible.builtin.user:
    name: "{{ node_exporter_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false

- name: Create textfile collector dir
  ansible.builtin.file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    mode: "0755"
  vars:
    node_exporter_group: "{{ node_exporter_user }}"

- name: Download node_exporter archive
  ansible.builtin.get_url:
    url: "{{ node_exporter_download_url }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    mode: "0644"

- name: Unarchive node_exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
    dest: "/tmp"
    remote_src: true

- name: Install binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}/node_exporter"
    dest: "{{ node_exporter_binary_dir }}/node_exporter"
    mode: "0755"
    owner: root
    group: root
  notify: Restart node_exporter

- name: Deploy /etc/default/node_exporter
  ansible.builtin.template:
    src: node_exporter.default.j2
    dest: /etc/default/node_exporter
    mode: "0644"
  notify: Restart node_exporter

- name: Deploy systemd unit
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: "0644"

- name: systemd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable and start node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    enabled: true
    state: started

# optional: UFW öffnen (nur wenn UFW installiert & gewünscht)
- name: Allow 9100/tcp via ufw
  ansible.builtin.command: ufw allow 9100/tcp
  changed_when: true
  failed_when: false
  when: ansible_facts.packages is defined and ('ufw' in ansible_facts.packages)
  tags: [ufw]

# Handlers
- name: Restart node_exporter
  ansible.builtin.systemd:
    name: node_exporter
    state: restarted
