- name: Ensure bot user exists
  user:
    name: "{{ bot_user }}"
    shell: /bin/bash
    home: "/home/{{ bot_user }}"
    create_home: yes

- name: Install required packages
  apt:
    name:
      - git
      - python3
      - python3-pip
    update_cache: yes
    state: present

- name: Clone Discord bot repository
  git:
    repo: "{{ bot_repo_url }}"
    dest: "{{ bot_repo_dest }}"
    version: main
    force: yes
    accept_hostkey: yes
  become: true
  become_user: "{{ bot_user }}"

- name: Install Python requirements
  pip:
    requirements: "{{ bot_repo_dest }}/requirements.txt"
    executable: pip3

- name: Create systemd service
  template:
    src: discord-bot.service.j2
    dest: "/etc/systemd/system/discord-bot.service"
    mode: '0644'

- name: Reload systemd and start bot
  systemd:
    name: discord-bot
    daemon_reload: yes
    enabled: yes
    state: restarted
