# roles/configure_discord_bot/tasks/main.yml

- name: Update APT cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - python3
      - python3-pip
      - git
    state: present

- name: Install discord.py via pip
  pip:
    name: discord.py
    executable: pip3

- name: Create bot directory
  file:
    path: /opt/discord-bot
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy simple bot script
  copy:
    dest: /opt/discord-bot/bot.py
    content: |
      import discord
      import os

      TOKEN = os.getenv('DISCORD_TOKEN')
      CHANNEL_ID = int(os.getenv('DISCORD_CHANNEL_ID'))

      client = discord.Client(intents=discord.Intents.default())

      @client.event
      async def on_ready():
          channel = client.get_channel(CHANNEL_ID)
          await channel.send('🤖 Bot is online!')

      client.run(TOKEN)
    mode: '0755'

- name: Create systemd service for Discord bot
  copy:
    dest: /etc/systemd/system/discord-bot.service
    content: |
      [Unit]
      Description=Discord Bot Service
      After=network.target

      [Service]
      Environment=DISCORD_TOKEN={{ discord_token }}
      Environment=DISCORD_CHANNEL_ID={{ discord_channel_id }}
      ExecStart=/usr/bin/python3 /opt/discord-bot/bot.py
      Restart=always
      User=root

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd
  command: systemctl daemon-reexec

- name: Enable and start discord-bot service
  systemd:
    name: discord-bot
    enabled: yes
    state: started
