---
- name: Ensure ISO directory exists
  file:
    path: "{{ iso_dir }}"
    state: directory
    mode: '0755'

- name: Ensure LXC template directory exists
  file:
    path: "{{ lxc_dir }}"
    state: directory
    mode: '0755'

### --- Debian ISO ---

- name: Fetch Debian ISO file list
  uri:
    url: "{{ debian_base_url }}"
    return_content: yes
  register: debian_html

- name: Extract latest Debian netinst ISO filename
  set_fact:
    debian_iso_filename: "{{ debian_html.content | regex_search('debian-[0-9.]+-amd64-netinst\\.iso') }}"

- name: Build Debian ISO URL
  set_fact:
    debian_iso_url: "{{ debian_base_url }}{{ debian_iso_filename }}"

- name: Download latest Debian ISO (if not present)
  get_url:
    url: "{{ debian_iso_url }}"
    dest: "{{ iso_dir }}/{{ debian_iso_filename }}"
    mode: '0644'
    force: no

### --- Ubuntu ISO ---

- name: Select latest Ubuntu LTS version
  set_fact:
    ubuntu_lts_version: "{{ ubuntu_lts_versions | sort | last }}"

- name: Select Ubuntu ISO filename
  set_fact:
    ubuntu_iso_filename: "{{ ubuntu_iso_filenames[ubuntu_lts_version] }}"

- name: Build Ubuntu ISO URL
  set_fact:
    ubuntu_iso_url: "{{ ubuntu_base_url }}{{ ubuntu_lts_version }}/{{ ubuntu_iso_filename }}"

- name: Download latest Ubuntu ISO (if not present)
  get_url:
    url: "{{ ubuntu_iso_url }}"
    dest: "{{ iso_dir }}/{{ ubuntu_iso_filename }}"
    mode: '0644'
    force: no

### --- LXC Templates via pveam ---

- name: Update Proxmox LXC template list
  command: pveam update

- name: Find latest Ubuntu 22.04 LXC template
  shell: "pveam available | grep ubuntu-22.04-standard | sort | tail -n 1 | awk '{print $2}'"
  register: ubuntu_lxc_template
  changed_when: false

- name: Download Ubuntu 22.04 LXC template
  command: "pveam download local {{ ubuntu_lxc_template.stdout }}"
  args:
    chdir: "{{ lxc_dir }}"

- name: Find latest Debian 12 LXC template
  shell: "pveam available | grep debian-12-standard | sort | tail -n 1 | awk '{print $2}'"
  register: debian_lxc_template
  changed_when: false

- name: Download Debian 12 LXC template
  command: "pveam download local {{ debian_lxc_template.stdout }}"
  args:
    chdir: "{{ lxc_dir }}"

### --- Discord Notification ---

- name: Send Discord notification
  uri:
    url: "{{ discordwebhook }}"
    method: POST
    headers:
      Content-Type: "application/json"
    body: |
      {
        "username": "Proxmox ISO Downloader",
        "embeds": [
          {
            "title": "✅ Proxmox ISO & LXC Templates updated",
            "color": 65280,
            "fields": [
              {"name": "Ubuntu ISO", "value": "{{ ubuntu_iso_filename }}", "inline": true},
              {"name": "Debian ISO", "value": "{{ debian_iso_filename }}", "inline": true},
              {"name": "Ubuntu LXC", "value": "{{ ubuntu_lxc_template.stdout }}", "inline": true},
              {"name": "Debian LXC", "value": "{{ debian_lxc_template.stdout }}", "inline": true}
            ],
            "timestamp": "{{ ansible_date_time.iso8601 }}"
          }
        ]
      }
    body_format: json
    status_code: 204
  delegate_to: localhost
  run_once: true
  ignore_errors: true
  become: false
