---
- name: Set directories and URLs
  set_fact:
    iso_dir: "/var/lib/vz/template/iso"
    lxc_dir: "/var/lib/vz/template/cache"
    ubuntu_base_url: "https://releases.ubuntu.com/"
    debian_base_url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/"

- name: Ensure ISO directory exists
  file:
    path: "{{ iso_dir }}"
    state: directory
    mode: '0755'

- name: Ensure LXC template directory exists
  file:
    path: "{{ lxc_dir }}"
    state: directory
    mode: '0755'

### --- Debian ISO ---

- name: Fetch Debian ISO file listing
  uri:
    url: "{{ debian_base_url }}"
    return_content: yes
  register: debian_html

- name: Extract latest Debian netinst ISO filename
  set_fact:
    debian_iso_filename: "{{ debian_html.content | regex_search('debian-[0-9.]+-amd64-netinst\\.iso') }}"

- name: Build Debian ISO URL
  set_fact:
    debian_iso_url: "{{ debian_base_url }}{{ debian_iso_filename }}"

- name: Download latest Debian ISO (if not exists)
  get_url:
    url: "{{ debian_iso_url }}"
    dest: "{{ iso_dir }}/{{ debian_iso_filename }}"
    mode: '0644'
    force: no

### --- Ubuntu ISO ---

- name: Define known supported Ubuntu LTS versions
  set_fact:
    ubuntu_lts_versions: [ '24.04', '22.04', '20.04', '18.04', '16.04' ]

- name: Determine latest Ubuntu LTS version
  set_fact:
    ubuntu_lts_version: "{{ ubuntu_lts_versions | sort | last }}"

- name: Define Ubuntu ISO filenames per LTS version
  set_fact:
    ubuntu_iso_filenames:
      '24.04': "ubuntu-24.04.2-live-server-amd64.iso"
      '22.04': "ubuntu-22.04.4-live-server-amd64.iso"
      '20.04': "ubuntu-20.04.6-live-server-amd64.iso"
      '18.04': "ubuntu-18.04.6-live-server-amd64.iso"
      '16.04': "ubuntu-16.04.7-server-amd64.iso"

- name: Determine Ubuntu ISO filename
  set_fact:
    ubuntu_iso_filename: "{{ ubuntu_iso_filenames[ubuntu_lts_version] }}"

- name: Build Ubuntu ISO URL
  set_fact:
    ubuntu_iso_url: "{{ ubuntu_base_url }}{{ ubuntu_lts_version }}/{{ ubuntu_iso_filename }}"

- name: Download latest Ubuntu ISO (if not exists)
  get_url:
    url: "{{ ubuntu_iso_url }}"
    dest: "{{ iso_dir }}/{{ ubuntu_iso_filename }}"
    mode: '0644'
    force: no

### --- LXC Templates via pveam ---

- name: Update Proxmox LXC template list
  command: pveam update

- name: Download Ubuntu 22.04 LXC template via Proxmox
  command: pveam download local ubuntu-22.04-standard_20240501_amd64.tar.zst
  args:
    chdir: /var/lib/vz/template/cache

- name: Download Debian 12 LXC template via Proxmox
  command: pveam download local debian-12-standard_20240501_amd64.tar.zst
  args:
    chdir: /var/lib/vz/template/cache
