---
- name: Set directories and URLs
  set_fact:
    iso_dir: "/var/lib/vz/template/iso"
    lxc_dir: "/var/lib/vz/template/cache"
    ubuntu_base_url: "https://releases.ubuntu.com/"
    debian_base_url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/"
    ubuntu_lxc_url: "https://images.linuxcontainers.org/images/ubuntu/jammy/amd64/default/latest/rootfs.tar.xz"
    debian_lxc_url: "https://images.linuxcontainers.org/images/debian/bookworm/amd64/default/latest/rootfs.tar.xz"

- name: Ensure ISO directory exists
  file:
    path: "{{ iso_dir }}"
    state: directory
    mode: '0755'

- name: Ensure LXC template directory exists
  file:
    path: "{{ lxc_dir }}"
    state: directory
    mode: '0755'

### --- Debian ISO ---

- name: Fetch Debian ISO file listing
  uri:
    url: "{{ debian_base_url }}"
    return_content: yes
  register: debian_html

- name: Extract latest Debian netinst ISO filename
  set_fact:
    debian_iso_filename: "{{ debian_html.content | regex_search('debian-[0-9.]+-amd64-netinst\\.iso') }}"

- name: Build Debian ISO URL
  set_fact:
    debian_iso_url: "{{ debian_base_url }}{{ debian_iso_filename }}"

- name: Download latest Debian ISO (if not exists)
  get_url:
    url: "{{ debian_iso_url }}"
    dest: "{{ iso_dir }}/{{ debian_iso_filename }}"
    mode: '0644'
    force: no

### --- Ubuntu ISO (statisch stabil) ---

- name: Define known supported Ubuntu LTS versions
  set_fact:
    ubuntu_lts_versions: [ '24.04', '22.04', '20.04', '18.04', '16.04' ]

- name: Determine latest Ubuntu LTS version
  set_fact:
    ubuntu_lts_version: "{{ ubuntu_lts_versions | sort | last }}"

- name: Build Ubuntu ISO URL
  set_fact:
    ubuntu_iso_url: "{{ ubuntu_base_url }}{{ ubuntu_lts_version }}/ubuntu-{{ ubuntu_lts_version }}-live-server-amd64.iso"

- name: Download latest Ubuntu ISO (if not exists)
  get_url:
    url: "{{ ubuntu_iso_url }}"
    dest: "{{ iso_dir }}/ubuntu-{{ ubuntu_lts_version }}-live-server-amd64.iso"
    mode: '0644'
    force: no

### --- LXC Templates ---

- name: Download Ubuntu LXC template
  get_url:
    url: "{{ ubuntu_lxc_url }}"
    dest: "{{ lxc_dir }}/ubuntu-jammy-latest.tar.xz"
    mode: '0644'
    force: yes

- name: Download Debian LXC template
  get_url:
    url: "{{ debian_lxc_url }}"
    dest: "{{ lxc_dir }}/debian-bookworm-latest.tar.xz"
    mode: '0644'
    force: yes
