---
- name: Deploy and configure a Discord bot in LXC
  hosts: discord_lxc
  become: true
  vars:
    discord_bot_repo: "https://github.com/dein-benutzername/dein-discord-bot.git"
    discord_bot_directory: "/opt/discord-bot"
    discord_bot_user: "discordbot"
    discord_bot_python_version: "3.11"
    discord_bot_service_name: "discord-bot"
    discordwebhook: "{{ discordwebhook }}"

  roles:
    - configure_discord_bot
