---
- hosts: proxmox
  become: true
  vars:
    iso_dir: "/var/lib/vz/template/iso"
    lxc_dir: "/var/lib/vz/template/cache"
    ubuntu_base_url: "https://releases.ubuntu.com/"
    debian_base_url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/"
    ubuntu_lts_versions: [ '24.04', '22.04', '20.04', '18.04', '16.04' ]
  roles:
    - download_proxmox_images
