---
- hosts: linux_lxc
  gather_facts: true
  vars:
    discordwebhook: "{{ discordwebhook }}"  # kommt aus Semaphore Variables
  tasks:
    - name: Upgrade all installed packages on Debian and Ubuntu
      apt:
        name: "*"
        state: latest
        update_cache: yes
        force_apt_get: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
        APT_LISTCHANGES_FRONTEND: none
      async: 600
      poll: 5
      when: ansible_distribution in ['Ubuntu', 'Debian']
      register: upgrade_result
      ignore_errors: true

    - name: Set upgrade result fact
      set_fact:
        upgrade_status: "{{ 'success' if upgrade_result is succeeded else 'failed' }}"

    - name: Set timestamp
      set_fact:
        upgrade_timestamp: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

- hosts: localhost
  gather_facts: false
  vars:
    target_group: "{{ groups['linux_lxc'] }}"
    notification_title: "Linux LXC Upgrade Report"
  roles:
    - discord_notify