---
- hosts: linux_lxc
  gather_facts: true
  roles:
    - update_system

- hosts: localhost
  gather_facts: false
  vars:
    target_group: "{{ groups['linux_lxc'] }}"
    notification_title: "System Update Report"
  roles:
    - discord_notify
