---
# Sicherstellen, dass das Basisverzeichnis existiert
- name: Ensure containers_root exists
  ansible.builtin.file:
    path: "{{ containers_root | default('/opt/containers') }}"
    state: directory
    mode: "0755"

# Pi-hole spezifische Verzeichnisse erstellen
- name: Create Pi-hole directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ containers_root | default('/opt/containers') }}/pihole"
    - "{{ containers_root | default('/opt/containers') }}/pihole/etc-pihole"
    - "{{ containers_root | default('/opt/containers') }}/pihole/etc-dnsmasq.d"

# docker-compose.yml bereitstellen
- name: Deploy Pi-hole docker-compose.yml
  ansible.builtin.copy:
    dest: "{{ containers_root | default('/opt/containers') }}/pihole/docker-compose.yml"
    mode: "0644"
    content: |
      services:
        pihole:
          image: pihole/pihole:latest
          container_name: pihole
          restart: unless-stopped
          network_mode: host
          environment:
            TZ: "{{ timezone }}"
            WEBPASSWORD: "{{ pihole_webpassword }}"
            DNSMASQ_USER: "root"
            FTLCONF_LOCAL_IPV4: "{{ pihole_ip }}"
            PIHOLE_DNS_: "{{ pihole_dns_1 }};{{ pihole_dns_2 }}{% if use_unbound %};127.0.0.1#5335{% endif %}"
          volumes:
            - ./etc-pihole:/etc/pihole
            - ./etc-dnsmasq.d:/etc/dnsmasq.d
          cap_add:
            - NET_ADMIN
      {% if use_unbound %}
        unbound:
          image: mvance/unbound:latest
          container_name: unbound
          restart: unless-stopped
          network_mode: host
          command: ["-q"]
      {% endif %}

# Compose-Projekt starten
- name: Bring up Pi-hole stack
  ansible.builtin.shell: docker compose up -d
  args:
    chdir: "{{ containers_root | default('/opt/containers') }}/pihole"
